services:
  web:
    image: ghcr.io/oodzchen/fruman:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS:-http://:80}
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
