export const ENTITY_STRIDE = 26

export const OFFSETS = {
  ID: 0,
  X: 1,
  Y: 2,
  RADIUS: 3,
  COLOR: 4,
  BORDER_COLOR: 5,
  FLAGS: 6, // 1=Visible, 2=Dead, 4=Vanished, 8=Rolling
  MOVE_DIR: 7,
  STATS_HEALTH_MAX: 8,
  STATS_HEALTH: 9,
  STATS_TOUGHNESS_MAX: 10,
  STATS_TOUGHNESS: 11,
  STATS_DEATH_ELAPSED: 12,
  STATS_SHAKE_DURATION: 13,
  STATS_SHAKE_ELAPSED: 14,
  STATS_SHAKE_INTENSITY: 15,
  STATS_SHAKE_DIR_X: 16,
  WEAPON_ACTIVE: 17,
  WEAPON_X: 18,
  WEAPON_Y: 19,
  WEAPON_ROT: 20,
  WEAPON_W: 21,
  WEAPON_H: 22,
  WEAPON_R: 23,
  ROLL_ANGLE: 24,
  LOCKED_TARGET_ID: 25,
}

export const FLAGS = {
  VISIBLE: 1,
  DEAD: 2,
  VANISHED: 4,
  ROLLING: 8,
  STAGGERED: 16,
}

export const MAX_ENTITIES = 2000
