export const ENTITY_STRIDE = 33

export const OFFSETS = {
  ID: 0,
  X: 1,
  Y: 2,
  RADIUS: 3,
  COLOR: 4,
  BORDER_COLOR: 5,
  FLAGS: 6, // 1=Visible, 2=Dead, 4=Vanished, 8=Rolling
  MOVE_DIR: 7,
  STATS_HEALTH_MAX: 8,
  STATS_HEALTH: 9,
  STATS_POSTURE_MAX: 10,
  STATS_POSTURE: 11,
  STATS_DEATH_ELAPSED: 12,
  STATS_SHAKE_DURATION: 13,
  STATS_SHAKE_ELAPSED: 14,
  STATS_SHAKE_INTENSITY: 15,
  STATS_SHAKE_DIR_X: 16,
  WEAPON_ACTIVE: 17,
  WEAPON_X: 18,
  WEAPON_Y: 19,
  WEAPON_ROT: 20,
  WEAPON_W: 21,
  WEAPON_H: 22,
  WEAPON_R: 23,
  WEAPON_TYPE: 24,
  WEAPON_DRAW: 25,
  WEAPON_DRAW_ACTIVE: 26,
  ROLL_ANGLE: 27,
  LOCKED_TARGET_ID: 28,
  FREE_AIM_ACTIVE: 29,
  FREE_AIM_X: 30,
  FREE_AIM_Y: 31,
  WEAPON_HAS_ARROW: 32,
}

export const FLAGS = {
  VISIBLE: 1,
  DEAD: 2,
  VANISHED: 4,
  ROLLING: 8,
  STAGGERED: 16,
  WEAPON_ATTACKING: 32,
  IS_PLAYER: 64,
  IN_COMBAT: 128,
  WEAPON_BLOCKING: 256,
  HUD_VISIBLE: 512,
}

export const WEAPON_TYPES = {
  SWORD: 0,
  SHORT_SWORD: 1,
  LONG_SWORD: 2,
  HAMMER: 3,
  BOW: 4,
  ARROW: 5,
} as const

export const MAX_ENTITIES = 2000
