export const ENTITY_STRIDE = 90

export const OFFSETS = {
  ID: 0,
  X: 1,
  Y: 2,
  RADIUS: 3,
  COLOR: 4,
  BORDER_COLOR: 5,
  FLAGS: 6, // 1=Visible, 2=Dead, 4=Vanished, 8=Rolling
  MOVE_DIR: 7,
  STATS_HEALTH_MAX: 8,
  STATS_HEALTH: 9,
  STATS_POSTURE_MAX: 10,
  STATS_POSTURE: 11,
  STATS_DEATH_ELAPSED: 12,
  STATS_SHAKE_DURATION: 13,
  STATS_SHAKE_ELAPSED: 14,
  STATS_SHAKE_INTENSITY: 15,
  STATS_SHAKE_DIR_X: 16,
  WEAPON_ACTIVE: 17,
  WEAPON_X: 18,
  WEAPON_Y: 19,
  WEAPON_ROT: 20,
  WEAPON_W: 21,
  WEAPON_H: 22,
  WEAPON_R: 23,
  WEAPON_TYPE: 24,
  WEAPON_DRAW: 25,
  WEAPON_DRAW_ACTIVE: 26,
  ROLL_ANGLE: 27,
  LOCKED_TARGET_ID: 28,
  FREE_AIM_ACTIVE: 29,
  FREE_AIM_X: 30,
  FREE_AIM_Y: 31,
  WEAPON_HAS_ARROW: 32,
  WEAPON_SLOT_MAIN_HAS: 33,
  WEAPON_SLOT_MAIN_TYPE: 34,
  WEAPON_SLOT_MAIN_W: 35,
  WEAPON_SLOT_MAIN_H: 36,
  WEAPON_SLOT_MAIN_AMMO: 37,
  WEAPON_SLOT_SECONDARY_HAS: 38,
  WEAPON_SLOT_SECONDARY_TYPE: 39,
  WEAPON_SLOT_SECONDARY_W: 40,
  WEAPON_SLOT_SECONDARY_H: 41,
  WEAPON_SLOT_SECONDARY_AMMO: 42,
  WEAPON_SLOT_ACTIVE: 43,
  WEAPON_SLOT_MAIN_SIZE: 44,
  WEAPON_SLOT_SECONDARY_SIZE: 45,
  WEAPON_SLOT_MAIN_MAX: 46,
  WEAPON_SLOT_SECONDARY_MAX: 47,
  GRAPPLE_ACTIVE: 48,
  GRAPPLE_TARGET_X: 49,
  GRAPPLE_TARGET_Y: 50,
  GRAPPLE_START_X: 51,
  GRAPPLE_START_Y: 52,
  GRAPPLE_VX: 53,
  GRAPPLE_VY: 54,
  ULTIMATE_COOLDOWN_RATIO: 55,
  ULTIMATE_READY: 56,
  ULTIMATE_SWORD_ACTIVE: 57,
  ULTIMATE_SWORD_X: 58,
  ULTIMATE_SWORD_GROUND_Y: 59,
  ULTIMATE_SWORD_RISE100: 60,
  ULTIMATE_SWORD_ALPHA100: 61,
  ULTIMATE_FLASH_TIMER100: 62,
  HAMMER_ULTIMATE_ACTIVE: 63, // 1 = 锤子绝招动画进行中
  HAMMER_ULTIMATE_IMPACT100: 64, // 冲击波进度 0-100
  SPEAR_ULTIMATE_ACTIVE: 65, // 1 = 枪类绝招幻影可见
  SPEAR_ULTIMATE_ALPHA100: 66, // 幻影透明度 0-100
  SPEAR_ULTIMATE_TOP_X: 67,
  SPEAR_ULTIMATE_TOP_Y: 68,
  SPEAR_ULTIMATE_TOP_ROT: 69,
  SPEAR_ULTIMATE_BOTTOM_X: 70,
  SPEAR_ULTIMATE_BOTTOM_Y: 71,
  SPEAR_ULTIMATE_BOTTOM_ROT: 72,
  SPEAR_ULTIMATE_W: 73,
  SPEAR_ULTIMATE_H: 74,
  SOLAR_SMALL: 75,
  SOLAR_LARGE: 76,
  SOLAR_LARGE_MAX: 77,
  BODY_HEIGHT: 78,
  FOLLOW_FLASH_PROGRESS: 79, // 绑定动画进度 1.0→0.0，>0 表示动画进行中
  UNBOND_FLASH_PROGRESS: 80, // 解绑动画进度 1.0→0.0，>0 表示动画进行中
  PLAYER_LEVEL: 81,
  PLAYER_EXP_RATIO100: 82, // 当前经验 / 升级所需经验 × 100（整数 0-100）
  BODY_PROFILE_INDEX: 83,
  RENDER_LAYER: 84,
  SKILL_HAS: 85, // 当前武器是否有技能：1=有，0=无
  SKILL_CHARGES: 86, // 技能剩余使用次数
  SKILL_MAX_CHARGES: 87, // 技能最大使用次数
  STATS_DAMAGE_TEXT_VALUE: 88, // 当帧需显示的受击数值
  STATS_DAMAGE_TEXT_TOKEN: 89, // 受击事件序号，用于前端去重
}

export const FLAGS = {
  VISIBLE: 1,
  DEAD: 2,
  VANISHED: 4,
  ROLLING: 8,
  STAGGERED: 16,
  WEAPON_ATTACKING: 32,
  IS_PLAYER: 64,
  IN_COMBAT: 128,
  WEAPON_BLOCKING: 256,
  HUD_VISIBLE: 512,
  CHECKPOINT: 1024,
  GRAPPLE_READY: 2048,
  GRAPPLE_ANCHOR: 4096,
  GRAPPLE_ANCHOR_HIGHLIGHT: 8192,
  SUN_PICKUP_SMALL: 16384,
  SUN_PICKUP_LARGE: 32768,
  HEALTH_BAR_FLASH: 65536,
  IS_FOLLOWING: 131072, // 跟随绑定动画进行中
  EXP_ORB: 262144,
  FOLLOW_BOUND: 524288, // 已绑定为同伴
  TERRAIN_DEBRIS: 1048576,
}

export const WEAPON_TYPES = {
  SWORD: 0,
  SHORT_SWORD: 1,
  LONG_SWORD: 2,
  SPEAR: 3,
  HAMMER: 4,
  BIG_HAMMER: 5,
  BOW: 6,
  ARROW: 7,
  HOOK: 8,
  GRAPE: 9,
  GRAPE_SHOT: 10,
  BOMB: 11,
} as const

export const MAX_ENTITIES = 2000
