import { ENTITY_STRIDE, MAX_ENTITIES } from './binaryProtocol'

export const EFFECT_STRIDE = 6
export const EFFECT_OFFSETS = {
  TYPE: 0,
  X: 1,
  Y: 2,
  COLOR: 3,
  RADIUS: 4,
  RENDER_LAYER: 5,
}

export const EFFECT_TYPES = {
  SPARK: 0,
  BLOOD: 1,
  DEATH: 2,
  SOUND: 3,
  HEAL: 4,
  CAMERA_SHAKE: 5,
  CHECKPOINT_PULSE: 6,
  CRIT_BURST: 7,
  PARRY_SPARK: 8,
  BOMB_EXPLOSION: 9,
} as const

export const SOUND_IDS = {
  SWORD_SWING_NORMAL: 0,
  SWORD_SWING_FINAL: 1,
  SWORD_PARRY: 2,
  BODY_HIT: 3,
  SWORD_HIT_OBSTACLE: 4,
  SWORD_BLOCK: 5,
  BOW_SNAP: 6,
  DEATH_SPLASH: 7,
  BODY_HIT_SHARP: 8,
  GRAPPLE_PULL_START: 9,
  SWORD_ULTIMATE_SPIN: 10,
  SWORD_ULTIMATE_GIANT_RISE: 11,
  HAMMER_ULTIMATE_LAND: 12,
  SPEAR_ULTIMATE_THRUST: 13,
  PICKUP_ITEM: 14,
  HEAVY_SWORD_HIT_GROUND: 15,
  BIG_HAMMER_HIT_ROCK: 16,
  GRAPE_FIRE: 17,
  BOMB_EXPLOSION: 18,
} as const

export const MAX_EFFECTS = 256
export const EFFECTS_BASE_OFFSET = MAX_ENTITIES * ENTITY_STRIDE
export const EFFECT_BUFFER_FLOATS = MAX_EFFECTS * EFFECT_STRIDE
export const ROPE_POINT_STRIDE = 2
export const MAX_ROPE_POINTS = 96
export const ROPE_POINTS_BASE_OFFSET =
  EFFECTS_BASE_OFFSET + EFFECT_BUFFER_FLOATS
export const ROPE_BUFFER_FLOATS = MAX_ROPE_POINTS * ROPE_POINT_STRIDE
export const STATE_BUFFER_FLOATS = ROPE_POINTS_BASE_OFFSET + ROPE_BUFFER_FLOATS
